# All key names are converted to lowercase by Viper

serverPort: :8080
persistence:
  redis: 
    addr: redis:6379
    password:
    db: 0

reqsPerSecond: 1
tokenConfigs:
  - 'abc123': 10
  - 'abc321': 15